# Manipulate data the MXNet way with `ndarray`

It's impossible to get anything done if we can't manipulate data. So let's start by introducing NDArrays, MXNet's primary tool for storing and transforming data. If you've worked with NumPy before, you'll notice that NDArrays are by design similar to NumPy's multi-dimensional array. However, they confer a few key advantages. First, NDArrays support asynchronous computation on CPU, GPU, and distributed cloud architectures. Second, they provide support for automatic differentiation. These properties make NDArray an ideal library for machine learning, both for researchers and engineers launching production systems.


## Getting started

In this chapter, we'll get you going with the basic functionality. Don't worry if you don't understand any of the basic math, like element-wise operations or normal distributions. In the next two chapters we'll take another pass at NDArray, teaching you both the math you'll need and how to realize it in code.

To get started, let's import `mxnet`. We'll also import `ndarray` from `mxnet` for convenience. We’ll make a habit of setting a random seed so that you always get the same results that we do.

In [2]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

Next, let's see how to create an NDArray, without any values initialized. Specifically, we'll create a 2D array (also called a *matrix*) with 3 rows and 4 columns.

In [4]:
x = nd.empty(shape=(3,4))
print(x)


[[  5.30887333e+25   4.58644987e-41   8.72613889e-38   0.00000000e+00]
 [  2.10587223e-37   0.00000000e+00   8.40779079e-45   0.00000000e+00]
 [  0.00000000e+00   1.26116862e-44   1.40129846e-44   4.58644987e-41]]
<NDArray 3x4 @cpu(0)>


The `empty` method just grabs some memory and hands us back a matrix without setting the values of any of its entries. But typically, we'll want our matrices initialized. Commonly, we want a matrix of all zeros. 

In [48]:
x = nd.zeros(shape=(3,5))
x


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

Similarly, `ndarray` has a function to create a matrix of all ones. 

In [49]:
x = nd.ones(shape=(3,4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

Often, we'll want to create arrays whose values are sampled randomly. This is especially common when we intend to use the array as a parameter in a neural network. In this snippet, we initialize with values drawn from a standard normal distribution.

In [50]:
y = nd.random_normal(shape=(3,4))
y


[[ 0.14867957 -0.21776067 -0.49851316  2.22578788]
 [-0.84815776 -0.68832648  0.07811152  0.84155577]
 [-0.38241303 -0.61584121 -0.05334064  0.01961165]]
<NDArray 3x4 @cpu(0)>

As in NumPy, the dimensions of each NDArray are accessible via the `.shape` attribute.

In [51]:
y.shape

(3, 4)

We can also query its size, which is equal to the product of the components of the shape. Together with the precision of the stored values, this tells us how much memory the array occupies.

In [52]:
y.size

12

## Operations

NDArray supports a large number of standard mathematical operations. Such as element-wise addition:

In [53]:
x + y


[[ 1.14867961  0.78223932  0.50148684  3.22578788]
 [ 0.15184224  0.31167352  1.07811153  1.84155583]
 [ 0.61758697  0.38415879  0.94665939  1.0196116 ]]
<NDArray 3x4 @cpu(0)>

Multiplication:

In [54]:
x * y


[[ 0.14867957 -0.21776067 -0.49851316  2.22578788]
 [-0.84815776 -0.68832648  0.07811152  0.84155577]
 [-0.38241303 -0.61584121 -0.05334064  0.01961165]]
<NDArray 3x4 @cpu(0)>

And exponentiation:

In [55]:
nd.exp(y)


[[ 1.16030109  0.80431789  0.60743314  9.26077652]
 [ 0.42820305  0.50241619  1.08124328  2.31997347]
 [ 0.68221325  0.54018629  0.948057    1.01980519]]
<NDArray 3x4 @cpu(0)>

We can also grab a matrix's transpose to compute a proper matrix-matrix product.

In [56]:
nd.dot(x, y.T)


[[ 1.65819359 -0.61681694 -1.03198326]
 [ 1.65819359 -0.61681694 -1.03198326]
 [ 1.65819359 -0.61681694 -1.03198326]]
<NDArray 3x3 @cpu(0)>

We'll explain these opoerations and present even more operators in the [linear algebra](P01-C03-linear-algebra.ipynb) chapter. But for now, we'll stick with the mechanics of working with NDArrays.

## In-place operations

In the previous example, every time we ran an operation, we allocated new memory to host its results. For example, if we write `y = x + y`, we will dereference the matrix that `y` used to point to and insted point it at the newly allocated memory. We can show this using Python's `id()` function, which tells us precisely which object a variable refers to.

In [57]:
print('id(y):', id(y))
y = y + x
print('id(y):', id(y))

id(y): 140571994896256
id(y): 140571994894576


To make better use of memory, we can perform operations in place, reusing already allocated memory. We can specify where to write the results of operations by assigning them with slice notation, e.g., `result[:] = ...`.

In [58]:
z = nd.zeros_like(x)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 140572040919864
id(z): 140572040919864


If we're not planning to re-use ``x``, then we can assign the result to ``x`` itself. There are two ways to do this in MXNet. 
1. By using slice notation x[:] = x op y
2. By using the op-equals operators like `+=`

In [ ]:
x += y
x