# Linear Algebra

Now that you can store and manipulate data, let's briefly review the subset of basic linear algebra that you'll need to understand most of the models. We'll introduce all the basic concepts, the corresponding mathematical notaiton, and their realization in code all in one place. If you're already confident basic linear algebra, free to skim or skip this chapter. 

In [25]:
import mxnet as mx
import mxnet.ndarray as nd

## Scalars

If you never studied linear algebra or machine learning, you're probably used to working with single numbers, like $42.0$ and know how to do basic things like add them together, multiply them. In mathematical notation, we'll represent salars with ordinary lower cased letters ($x$, $y$, $z$). In MXNet, we can work with scalars by creating NDArrays with just one element. 

In [26]:
x = nd.array([3.0]) 
y = nd.array([2.0])
print(x + y)
print(x * y)
print(x / y)
print(nd.power(x,y))


[ 5.]
<NDArray 1 @cpu(0)>

[ 6.]
<NDArray 1 @cpu(0)>

[ 1.5]
<NDArray 1 @cpu(0)>

[ 9.]
<NDArray 1 @cpu(0)>


We can convert NDArrays to Python floats by calling their ``.asscalar()

In [27]:
x.asscalar()

3.0

## Vectors 
You can think of vectors are simply a list of numbers ([1.0,3.0,4.0,2.0]). A vector could represent numerical features of some real-world person or object, like the last-record measurements across various vital signs for a patient in the hospital. In math notation, we'll always denote vectors as bold-faced lower-cased letters ($\boldsymbol{u}$, $\boldsymbol{v}$, $\boldsymbol{w})$. In MXNet, we work with vectors via 1D NDArrays with an arbitrary number of components.

In [32]:
u = nd.zeros(shape=10)
v = nd.ones(shape=10)
print(u)
print(v)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
<NDArray 10 @cpu(0)>

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
<NDArray 10 @cpu(0)>


We can refer to any element of a vector by using a subscript. For example, we can refer to the $4$th element of $\boldsymbol{u}$ by $u_4$. Note that the element $u_4$ is a scalar, so we don't bold-face the font when referring to it.

## Matrices

Just as vectors are an extension of scalars from 0 to 1 dimension, matrices generalization vectors to two dimensions. Matrices, which we'll denote with capital letters ($A$, $B$, $C$) are 2D arrays. 

In [34]:
A = nd.random_normal(shape=(5,4))
B = nd.random_normal(shape=(5,4))

In [ ]:
Matrices are useful data structures, they allow us to organize data that has different modalities of variation. For example, returning to the example of medical data, rows in our matri

## Element-wise operations

Oftentimes, we want to perform element-wise operations. This means that we perform a scalar operation on the corresponding elements of two vectors. So given any two vectors $\boldsymbol{u}$ and $\boldsymbol{v}$ *of the same shape*, and a scalar function $f$, we can perform the operation  we produce vector $\boldsymbol{c} = f(\boldsymbol{u},\boldsymbol{v})$ by setting $c_i \gets f(u_i, v_i)$.

In [33]:
print(u)
print(v) 
print(u + v)
print(u - v)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
<NDArray 10 @cpu(0)>

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
<NDArray 10 @cpu(0)>

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
<NDArray 10 @cpu(0)>

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
<NDArray 10 @cpu(0)>


## Dot products

## Matrix-vector multiplication

## Matrix-matrix multiplication

In [ ]:
Broadcasting